export enum AllTypeActions {
	GET_BLACKDOMAINS = 'GET_BLACKDOMAINS',
	CREATE_BLACKDOMAIN = 'CREATE_BLACKDOMAIN',
	UPDATE_BLACKDOMAIN = 'UPDATE_BLACKDOMAIN',
	DELETE_BLACKDOMAIN = 'DELETE_BLACKDOMAIN',
	DELETE_MULTIPLE_BLACKDOMAIN = 'DELETE_MULTIPLE_BLACKDOMAIN',
	SYSTEM_MESSAGE_SHOW = 'SYSTEM_MESSAGE_SHOW',
	SYSTEM_MESSAGE_HIDE = 'SYSTEM_MESSAGE_HIDE',
}
