export enum AllTypeActions {
  GET_BLACKDOMAINS = "GET_BLACKDOMAINS",
  CREATE_BLACKDOMAIN = "CREATE_BLACKDOMAIN",
  UPDATE_BLACKDOMAIN = "UPDATE_BLACKDOMAIN",
  DELETE_BLACKDOMAIN = "DELETE_BLACKDOMAIN",
  DELETE_MULTIPLE_BLACKDOMAIN = "DELETE_MULTIPLE_BLACKDOMAIN",
  SYSTEM_MESSAGE_SHOW = "SYSTEM_MESSAGE_SHOW",
  SYSTEM_MESSAGE_HIDE = "SYSTEM_MESSAGE_HIDE",

  GET_POSTS = "GET_POSTS",
  CREATE_DATAS = "CREATE_DATAS",
  UPDATE_DATAS = "UPDATE_DATAS",
  DELETE_DATAS = "DELETE_DATAS",
  DELETE_MULTIPLE_DATAS = "DELETE_MULTIPLE_DATAS",
}
